### ISSUE TITLE
BuildTag Functions

### ISSUE THREAD

**Issue by ObsidianPhoenix** [DarqueWarrior/team#14]
I've added three new methods in my fork:

* Get-BuildTags
* Add-BuildTag
* Remove-BuildTag

I'd like to start a PR, but before I do, would you mind running a quick review of the commit? I've tried to maintain relative consistency with the existing code, but I've not worked in a lot of modules before.

https://github.com/ObsidianPhoenix/team/commit/ab80bb9e8ed13f7c7422577744bd8f6040293115

One thing of note, I modified _buildUrl. The Tags require another level below the item Id. So I extracted the code to a common method. I had some issues with `$Logs` causing issues, so I needed an if to cope with it, not sure if thats the best way to handle it.

Thanks

**Comment by DarqueWarrior** [comment]
I will take a look. I am traveling for work so forgive any delays. First I can see if you will want to move the s from Get-BuildTags. Should just be Get-BuildTag. That is a PowerShell convention.  Thanks so much for your support.

**Comment by ObsidianPhoenix** [comment]
Thanks. Will do. I'm also realising I need to be able to change the KeepForever Flag on the build, will need to add a method for that.

**Comment by ObsidianPhoenix** [comment]
I've updated the `Get-BuildTags` method.  I've also added a few additional Methods.

* Get-BuildArtifact
* Update-Build

`Update-Build` Will update two properties on the build: KeepForever and BuildNumber. The Api can support some additional properties, but some of them are write-once, and others I didn't feel made much sense to change. Personally I only need KeepForever.

https://www.visualstudio.com/en-us/docs/integrate/api/build/builds#update-a-build

**Comment by DarqueWarrior** [comment]
Reviewing now.

**Comment by DarqueWarrior** [comment]
I might suggest you format the Resource of Get-BuildArtifact. Or pull out something useful from it for that column like DownloadUrl.

Update-Build, Remove-BuildTag should use SupportsShouldProcess = $true and call $pscmdlet.ShouldProcess and have a Force flag.
Add-BuildTag might need the same, but for some reason I am on the fence with that one.

Because the build API version is used in more than one place now I would make it a const in the file so we only have to change once.

I would add some pester tests for the new functions.

Otherwise, looks good. I have to hop on a plane but I will continue to review.  You can issue a PR and we can work through it there if you like.

**Comment by DarqueWarrior** [comment]
I have changed a couple of things. I will push them after I am done.  
Fixed issue with -Logs flag when getting logs from build.
Changed order of Add-BuildTag params so you can a tags without requiring the -Tags parameter to be called out.  It is now position 0 and be passed by position as well as name.
Going to add some help examples.
Formatted the code.
I am still poking around but I wanted to let you know. All and all I like what you have done.

**Comment by ObsidianPhoenix** [comment]
Thanks. We're approaching Code Freeze here, but hopefully I'll be able to spend time updating it next week.

**Comment by DarqueWarrior** [comment]
Perfect I will submit any changes from my end soon.

**Comment by ObsidianPhoenix** [comment]
Have you had a chance to commit your changes yet? Not seeing them on my end, but I could just be looking in the wrong location? Still getting to grips with git.

**Comment by DarqueWarrior** [comment]
I released a new version a few days ago.  Make sure you sync the forks then merge master into your working branch.

**Comment by DarqueWarrior** [comment]
Let me double check.  I might still have on my machine.

**Comment by DarqueWarrior** [comment]
OK there now. Be sure and sync with master because I pushed a new version.

**Comment by ObsidianPhoenix** [comment]
I've pulled the latest master into my fork. Still not seeing your changes. I was expecting to see them on my fork in the Add-BuildTag branch. Am I just being stupid?

**Comment by DarqueWarrior** [comment]
I missed this the first time I tried to push. ! [remote rejected] master -> master (permission denied)

**Comment by DarqueWarrior** [comment]
Can you grant me permissions to push my changes?

**Comment by ObsidianPhoenix** [comment]
That'll do it. Just granted you collaborator rights. Should that be enough?

**Comment by DarqueWarrior** [comment]
Must not be still getting permission denied.  Is master locked down?

**Comment by DarqueWarrior** [comment]
Just issue a proper PR and I will make my changes there.  I have my repo here with the changes.

**Comment by ObsidianPhoenix** [comment]
It's not locked down by the looks of it. But I haven't merged my changes into my master branch yet, which may be the culprit. Let me update with your suggestions and I'll issue a PR.

**Comment by DarqueWarrior** [comment]
Merged into review branch.

**Comment by DarqueWarrior** [comment]
No issues. I also just changed how help is written. You can now do it in Markdown with PlatyPS.  I am working on publishing your changes now.
